# Generated by Django 3.0.8 on 2022-11-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaccinationsepid_vaccinationsnat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinatedPersonsNat',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('KIDS', 'Дети'), ('ADULTS', 'Взрослые')], max_length=10)),
                ('age', models.TextField()),
                ('age_description', models.TextField(blank=True)),
                ('at_risk', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=3)),
                ('risk_description', models.TextField(blank=True)),
                ('first_revac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_revac', to='core.Vaccinations')),
                ('first_vaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_vaccin', to='core.Vaccinations')),
                ('fourth_vaccin_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_fourth_vaccin_risk', to='core.Vaccinations')),
                ('revaccintaion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_revaccintaion', to='core.Vaccinations')),
                ('second_revac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_revac', to='core.Vaccinations')),
                ('second_vaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_vaccin', to='core.Vaccinations')),
                ('third_revac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_revac', to='core.Vaccinations')),
                ('third_vaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin', to='core.Vaccinations')),
                ('third_vaccin_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin_risk', to='core.Vaccinations')),
                ('vaccintaion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_vaccintaion', to='core.Vaccinations')),
            ],
        ),
    ]
