# Generated by Django 3.0.8 on 2022-11-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vaccinatedpersonsnat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinatedpersonsnat',
            options={'verbose_name': 'Человек по нацкалендарю', 'verbose_name_plural': 'Люди по нацкалендарю'},
        ),
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='first_revac',
        ),
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='first_vaccin',
        ),
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='second_vaccin',
        ),
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='third_vaccin',
        ),
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='vaccintaion',
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='first_revac_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_revac_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='first_revac_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_revac_two', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='first_vaccin_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_vaccin_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='first_vaccin_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_vaccin_three', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='first_vaccin_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_first_vaccin_two', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='second_vaccin_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_vaccin_four', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='second_vaccin_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_vaccin_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='second_vaccin_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_vaccin_three', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='second_vaccin_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_second_vaccin_two', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='third_vaccin_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin_four', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='third_vaccin_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='third_vaccin_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin_three', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='third_vaccin_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_third_vaccin_two', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='vaccintaion_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_vaccintaion_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='vaccintaion_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_vaccintaion_three', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='vaccintaion_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_vaccintaion_two', to='core.Vaccinations'),
        ),
    ]
