# Generated by Django 3.0.8 on 2022-11-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221120_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinatedpersonsnat',
            name='revaccintaion',
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='revaccintaion_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_revaccintaion_one', to='core.Vaccinations'),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='revaccintaion_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vac_revaccintaion_two', to='core.Vaccinations'),
        ),
    ]
