# Generated by Django 3.0.8 on 2022-11-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221120_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationsepid',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations_epid', to='core.Vaccinations'),
        ),
        migrations.AlterField(
            model_name='vaccinationsnat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations_nat', to='core.Vaccinations'),
        ),
    ]
