# Generated by Django 3.0.8 on 2022-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221122_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='revaccintaion_one_descript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccinatedpersonsnat',
            name='vaccintaion_one_descript',
            field=models.TextField(blank=True),
        ),
    ]
