# Generated by Django 3.0.8 on 2022-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221129_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinations',
            name='type',
            field=models.CharField(choices=[('ALL', 'Общ'), ('NAT', 'Нац'), ('EPID', 'Эпид')], default='Общ', max_length=5),
        ),
    ]
